
version: '3.8'

services:
  db_agenda:
    build: ./database
    container_name: db_agenda
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agenda
    volumes:
      - db_data:/var/lib/mysql

  backend_agenda:
    build: ./backend
    container_name: backend_agenda
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db_agenda
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=agenda
    depends_on:
      - db_agenda

  frontend_agenda:
    build: ./frontend
    container_name: frontend_agenda
    ports:
      - "8080:80"
    depends_on:
      - backend_agenda

volumes:
  db_data:
