version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_agenda
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agenda
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: backend_agenda
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=agenda
      - DB_PORT=3306
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["npm", "start"]

  frontend:
    build: ./frontend
    container_name: frontend_agenda
    restart: always
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true  
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  db_data: 
